# Generated by Django 5.1.5 on 2026-04-10 12:21

from django.db import migrations, models


def seed_bid_options(apps, schema_editor):
    BidPlatform = apps.get_model("bids", "BidPlatform")
    BidProfile = apps.get_model("bids", "BidProfile")

    platforms = [
        ("Upwork", "upwork", 10),
        ("Freelancer", "freelancer", 20),
    ]
    profiles = [
        ("Profile1", "Profile1", 10),
        ("Profile2", "Profile2", 20),
        ("Profile3", "Profile3", 30),
        ("Profile4", "Profile4", 40),
    ]

    for name, value, sort_order in platforms:
        BidPlatform.objects.update_or_create(
            value=value,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )

    for name, value, sort_order in profiles:
        BidProfile.objects.update_or_create(
            value=value,
            defaults={"name": name, "sort_order": sort_order, "is_active": True},
        )


def remove_seeded_bid_options(apps, schema_editor):
    BidPlatform = apps.get_model("bids", "BidPlatform")
    BidProfile = apps.get_model("bids", "BidProfile")

    BidPlatform.objects.filter(value__in=["upwork", "freelancer"]).delete()
    BidProfile.objects.filter(value__in=["Profile1", "Profile2", "Profile3", "Profile4"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_is_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BidProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='bid',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(seed_bid_options, remove_seeded_bid_options),
    ]
