# Generated by Django 5.1.5 on 2026-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
